id: A5F58542F
title: 'Udayin: mānāpya'
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:19:56.974848
  last_modified_at: 2022-03-01 22:19:56.974851
