id: A5F58542F
title: Pratikriyāvastūddāna
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:19:56.966826
  last_modified_at: 2022-03-01 22:19:56.966831
