id: A5F58542F
title: 'Aśvaka & Punarvasaka: pravāsanīyaṃ karma'
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:19:56.962868
  last_modified_at: 2022-03-01 22:19:56.962874
