id: A5F58542F
title: 'Udayin: mūlāpakaṛṣa'
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:19:56.978501
  last_modified_at: 2022-03-01 22:19:56.978554
