id: A5F58542F
title: 'Uttara: pratisaṃharanīyaṃ karma'
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:19:56.988724
  last_modified_at: 2022-03-01 22:19:56.988727
