id: A5F58542F
title: 'Śreyaka: nigarhanīyaṃ karma'
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:19:56.991962
  last_modified_at: 2022-03-01 22:19:56.991968
